
#include "frontend/my.h"

#include "config.h"
#include "system.h"
#include "ansidecl.h"
#include "coretypes.h"

#include "toplev.h"

#include "diagnostic-core.h"
#include "input.h"

#include "tm.h"

#include "hash-set.h"
#include "machmode.h"
#include "vec.h"
#include "double-int.h"
#include "input.h"
#include "alias.h"
#include "symtab.h"
#include "options.h"
#include "wide-int.h"
#include "inchash.h"

#include "tree.h"
#include "fold-const.h"
#include "tree-dump.h"
#include "tree-iterator.h"

#include "tree-ssa-operands.h"
#include "tree-pass.h"
#include "tree-ssa-alias.h"
#include "bitmap.h"
#include "symtab.h"

#include "hard-reg-set.h"
#include "function.h"
#include "langhooks-def.h"
#include "langhooks.h"
#include "stringpool.h"
#include "is-a.h"

#include "gimple-expr.h"

#include "predict.h"
#include "basic-block.h"
#include "gimple.h"
#include "gimplify.h"
#include "ipa-ref.h"
#include "lto-streamer.h"
#include "cgraph.h"
#include "opts.h"

#include "print-tree.h"
#include "tree-cfg.h"

#include "joke-lang.h"
#include "joke1.h"


struct GTY(()) lang_identifier {
  struct tree_identifier common;
};

union GTY((desc("TREE_CODE(&%h.node)"))) lang_tree_node {
        union GTY((tag ("1"))) tree_node node;
};

struct GTY(()) lang_type {
  char dummy; 
};

/* Language-specific declaration information.  */

struct GTY(()) lang_decl {
  char dummy; 
};

struct GTY(()) language_function {
  char dummy;
};

vec<tree, va_gc> * joke_global_decls_vec = NULL;

/* language hooks */
struct lang_hooks lang_hooks = LANG_HOOKS_INITIALIZER;

/* Initialization routine for the joke1 (compiler) options */
void joke_init_options (unsigned int, struct cl_decoded_option *) {
  /* CL_joke is automatically generated by the GCC build process */
  return;
}

/* handle specific option - called by opts.c */
bool joke_handle_option (size_t scode, const char *arg,
		   int value ATTRIBUTE_UNUSED, int kind ATTRIBUTE_UNUSED,
		   location_t loc ATTRIBUTE_UNUSED,
		   const struct cl_option_handlers *handlers ATTRIBUTE_UNUSED) {
  enum opt_code code = (enum opt_code) scode;
  
  printf("Option: %s\n", arg); //zde by se měly řešit argumenty. Viz gcc/c-family/c-opts.c

  return true;
}

/* The language hooks gets called whenever all options and arguments are
 * parsed/read in the by options sub-component. This might be used for
 * further validation checks 
 *
 * If this function returns NOT 0, the middle-end/back-end of GCC WON'T
 * be called (this is for example used to emit pre-processing code only in
 * the C/C++ front-end)
 */
bool joke_post_options (const char **) {
  flag_excess_precision_cmdline = EXCESS_PRECISION_FAST;
  
  return 0;
}

/* This language hook gets called in decode_options to determine the front-end language mask. 
 * It should return the corresponding CL_*, in this case CL_joke.
 */
unsigned int joke_option_lang_mask(void) {
  return CL_joke;
}

/* language dependent parser setup  */
bool joke_init (void) {
  build_common_tree_nodes (flag_signed_char, false);

  return true;
}

void joke_parse_input_files(const char** filenames, unsigned filename_count) {
  
  for(unsigned i = 0; i < 1; i++) {
    printf("Parsing: %s\n", filenames[i]);
    parseFile(filenames[i], &joke_global_decls_vec);
  }

  if(filename_count > 1)
  {
    printf("Can compile just one file at the time!\n");
    for(unsigned x = 1; x < filename_count; x++)
      printf("Skipping.. %s\n", filenames[x]);
  }
  
  // if(flag_aaa) printf("Flag aaa is on\n");
  // else printf("Flag aaa is off\n");

  //execute parser from joke-lang.c here

  /////////////////////////////////
  // my_test();
  /////////////////////////////////
}

/* parsing language hook */
void joke_parse_file () {
  joke_parse_input_files (in_fnames, num_in_fnames);
}

/* language dependent wrapup */
void joke_finish (void) {
}

static bool joke_mark_addressable (tree /*exp*/) {
	gcc_unreachable ();
}
  
static tree joke_type_for_size (unsigned /*precision*/, int /*unsignedp*/) {
	gcc_unreachable ();
}

static tree joke_type_for_mode (enum machine_mode /*mode*/, int /*unsignedp*/) {
	gcc_unreachable ();
}

static tree pushdecl (tree /*decl*/) {
	gcc_unreachable ();
}

static tree getdecls (void) {
	return NULL;
}

/* flush global declarations */
void joke_write_globals (void) 
{  
  tree *vec = vec_safe_address(joke_global_decls_vec);
  int len = vec_safe_length(joke_global_decls_vec);
  wrapup_global_declarations (vec, len);
  emit_debug_global_declarations (vec, len);
  vec_free (joke_global_decls_vec);
  
  symtab->finalize_compilation_unit( );
}

static bool global_bindings_p (void) {
	gcc_unreachable ();
}

tree convert (tree /*type*/, tree /*expr*/) {
	return NULL;
}

#include "debug.h" 
#include "gt-joke-joke1.h"
#include "gtype-joke.h"
